language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - sudo apt-get update
install:
  - pip install -e .
  - pip install -r requirements/test.txt Django==$DJANGO
script:
  - django-admin.py test redis_metrics --settings=redis_metrics.tests.settings
env:
  - DJANGO=1.4.15
  - DJANGO=1.6.7
  - DJANGO=1.7
