language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - export PIP_USE_MIRRORS=true
  - sudo apt-get update
install:
  - pip install -e .
  - pip install -r requirements/test.txt Django==$DJANGO
script:
  - django-admin.py test redis_metrics --settings=redis_metrics.tests.settings
env:
  - DJANGO=1.4.22
  - DJANGO=1.7.10
  - DJANGO=1.8.6
